"""empty message

Revision ID: 0a6bc7f6124e
Revises: 72449dda8750
Create Date: 2020-11-26 15:02:36.133539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6bc7f6124e'
down_revision = '72449dda8750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('schema_rootpage', table_name='schema')
    op.drop_table('schema')
    op.drop_table('dbptr')
    op.drop_table('map')
    op.drop_table('freelist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelist',
    sa.Column('pgno', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('pgno')
    )
    op.create_table('map',
    sa.Column('pgno', sa.INTEGER(), nullable=False),
    sa.Column('maxlen', sa.INTEGER(), nullable=True),
    sa.Column('intkey', sa.NullType(), nullable=True),
    sa.Column('root', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('pgno')
    )
    op.create_table('dbptr',
    sa.Column('pgno', sa.NullType(), nullable=False),
    sa.Column('child', sa.NullType(), nullable=False),
    sa.PrimaryKeyConstraint('pgno', 'child')
    )
    op.create_table('schema',
    sa.Column('type', sa.NullType(), nullable=True),
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('tbl_name', sa.NullType(), nullable=True),
    sa.Column('rootpage', sa.NullType(), nullable=True),
    sa.Column('sql', sa.NullType(), nullable=True)
    )
    op.create_index('schema_rootpage', 'schema', ['rootpage'], unique=False)
    op.drop_table('lesson')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
