"""empty message

Revision ID: 72449dda8750
Revises: 9544958768be
Create Date: 2020-11-22 11:51:28.443891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72449dda8750'
down_revision = '9544958768be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'locked')
    # ### end Alembic commands ###
